backend:
  name: github
  repo: Jashk120/blog-posts
  branch: main

publish_mode: editorial_workflow

media_folder: public/images
public_folder: /images

collections:
  - name: posts
    label: Posts
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string, required: false }
      - { label: Body, name: body, widget: markdown }
